name: Trivy Helm Scan



on:

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]



jobs:

  trivy-scan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - uses: aquasecurity/trivy-action@master

        with:

          # Specify your Helm chart directory

          context: charts/

          # Set output format to SARIF

          output: sarif

      - uses: github/codeql-action/upload-sarif@v2

        with:

          sarif_file: trivy-report.sarif

          category: trivy



